Fixed a ClassCastException bug caused by an erroneous unit type info.
java.lang.ClassCastException: scala.runtime.BoxedUnit cannot be cast to java.lang.Void